// Lumina Dark 테마 설정 (stitch_dark_card_dashboard/code.html 기준 이식)
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'secondary-container': '#571bc1',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-high': '#2a2a2a',
        'primary-container': '#00f0ff',
        'on-secondary-fixed-variant': '#5516be',
        'on-tertiary': '#003824',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'on-surface-variant': '#b9cacb',
        'secondary-fixed': '#e9ddff',
        'on-tertiary-fixed-variant': '#005236',
        'on-surface': '#e5e2e1',
        'inverse-primary': '#006970',
        'surface-bright': '#3a3939',
        'on-primary': '#00363a',
        'surface-tint': '#00dbe9',
        primary: '#dbfcff',
        'on-background': '#e5e2e1',
        'on-secondary-fixed': '#23005c',
        'surface-container': '#201f1f',
        error: '#ffb4ab',
        'tertiary-container': '#65f2b5',
        'secondary-fixed-dim': '#d0bcff',
        outline: '#849495',
        'inverse-surface': '#e5e2e1',
        'tertiary-fixed': '#6ffbbe',
        'inverse-on-surface': '#313030',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#002022',
        surface: '#131313',
        'on-primary-container': '#006970',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3b494b',
        'on-secondary': '#3c0091',
        'error-container': '#93000a',
        'on-secondary-container': '#c4abff',
        'primary-fixed': '#7df4ff',
        'on-tertiary-fixed': '#002113',
        secondary: '#d0bcff',
        'surface-dim': '#131313',
        'on-tertiary-container': '#006d4a',
        tertiary: '#d8ffe7',
        background: '#131313',
        'primary-fixed-dim': '#00dbe9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '1rem',
        margin: '2rem',
        xl: '3rem',
        md: '1.5rem',
        xs: '0.5rem',
        gutter: '1.5rem',
        lg: '2rem',
        unit: '4px',
      },
      // 영문은 Inter, 한글은 Noto Sans KR (Inter에 한글 글리프 없어 자동 fallback)
      fontFamily: {
        'body-lg': ['Inter', 'Noto Sans KR'],
        'label-md': ['Inter', 'Noto Sans KR'],
        'label-sm': ['Inter', 'Noto Sans KR'],
        'headline-md': ['Inter', 'Noto Sans KR'],
        'body-md': ['Inter', 'Noto Sans KR'],
        'headline-xl': ['Inter', 'Noto Sans KR'],
        'headline-lg': ['Inter', 'Noto Sans KR'],
        'body-sm': ['Inter', 'Noto Sans KR'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '1', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
